project: Ethio-ASR-smoke-test
output_dir: /blue/rcstudents/btulu/Projects/Ethio-ASR/models
seed: 42
pretrained_model: ajesujoba/AfriHuBERT
freeze_feature_encoder: true
add_final_layer_adapter: false
batch_size: 4
gradient_accumulation_steps: 2
num_epochs: 1
max_steps: 20
learning_rate: 0.0003
warmup_ratio: 0.1
fp16: false
bf16: true
gradient_checkpointing: true
save_steps: 20
eval_steps: 10
logging_steps: 1
save_total_limit: 1
use_custom_dataset: false
dataset_path: badrex/waxalNLP-ethiopic-final
train_split: train
eval_split: validation
language: all
sample: true
sample_size: 200
add_language_tokens: true
apply_accent_replacements: true
character_set: " !#$%&'*+,-.0123456789=?@abcdefghijklmnopqrstuvwxyzሀሁሂሃሄህሆሇለሉሊላሌልሎሏሐሑሒሓሔሕሖሗመሙሚማሜምሞሟሠሡሢሣሤሥሦሧረሩሪራሬርሮሯሰሱሲሳሴስሶሷሸሹሺሻሼሽሾሿቀቁቂቃቄቅቆቇቈቊቋቌቍቐቑቒቓቔቕቖቘቚቛቜቝበቡቢባቤብቦቧቨቩቪቫቬቭቮቯተቱቲታቴትቶቷቸቹቺቻቼችቾቿኀኁኂኃኄኅኆኇኈኊኋኌኍነኑኒናኔንኖኗኘኙኚኛኜኝኞኟአኡኢኣኤእኦኧከኩኪካኬክኮኯኰኲኳኴኵኸኹኺኻኼኽኾዀዂዃዄዅወዉዊዋዌውዎዏዐዑዒዓዔዕዖዘዙዚዛዜዝዞዟዠዡዢዣዤዥዦዧየዩዪያዬይዮዯደዱዲዳዴድዶዷዸዹዺዻዼዽዾዿጀጁጂጃጄጅጆጇገጉጊጋጌግጎጏጐጒጓጔጕጘጙጚጛጜጝጞጟጠጡጢጣጤጥጦጧጨጩጪጫጬጭጮጯጰጱጲጳጴጵጶጷጸጹጺጻጼጽጾጿፀፁፂፃፄፅፆፇፈፉፊፋፌፍፎፏፐፑፒፓፔፕፖፗፘፙፚ፠፡።፣፤፥፦፧፨፩፪፫፬፭፮፯፰፱፲፳፴፵፶፷፸፹፺፻፼€"
