project: Ethio-ASR-paper-afrihubert-fp32
output_dir: /blue/rcstudents/btulu/Projects/Ethio-ASR/models
seed: 42
pretrained_model: ajesujoba/AfriHuBERT
freeze_feature_encoder: true
add_final_layer_adapter: false
batch_size: 4
gradient_accumulation_steps: 8
num_epochs: 7
max_steps: 36800
learning_rate: 0.00005    # paper hint; AfriHuBERT requires fp32 + lower LR
warmup_ratio: 0.1
fp16: false
bf16: false               # fp32 - paper says AfriHuBERT needs this
gradient_checkpointing: true
save_steps: 800
eval_steps: 800
logging_steps: 25
save_total_limit: 2
use_custom_dataset: false
dataset_path: badrex/waxalNLP-ethiopic-final
train_split: train
eval_split: validation
language: all
sample: false
sample_size: 197634
add_language_tokens: true
apply_accent_replacements: true
character_set: " !#$%&'*+,-.0123456789=?@abcdefghijklmnopqrstuvwxyzሀሁሂሃሄህሆሇለሉሊላሌልሎሏሐሑሒሓሔሕሖሗመሙሚማሜምሞሟሠሡሢሣሤሥሦሧረሩሪራሬርሮሯሰሱሲሳሴስሶሷሸሹሺሻሼሽሾሿቀቁቂቃቄቅቆቇቈቊቋቌቍቐቑቒቓቔቕቖቘቚቛቜቝበቡቢባቤብቦቧቨቩቪቫቬቭቮቯተቱቲታቴትቶቷቸቹቺቻቼችቾቿኀኁኂኃኄኅኆኇኈኊኋኌኍነኑኒናኔንኖኗኘኙኚኛኜኝኞኟአኡኢኣኤእኦኧከኩኪካኬክኮኯኰኲኳኴኵኸኹኺኻኼኽኾዀዂዃዄዅወዉዊዋዌውዎዏዐዑዒዓዔዕዖዘዙዚዛዜዝዞዟዠዡዢዣዤዥዦዧየዩዪያዬይዮዯደዱዲዳዴድዶዷዸዹዺዻዼዽዾዿጀጁጂጃጄጅጆጇገጉጊጋጌግጎጏጐጒጓጔጕጘጙጚጛጜጝጞጟጠጡጢጣጤጥጦጧጨጩጪጫጬጭጮጯጰጱጲጳጴጵጶጷጸጹጺጻጼጽጾጿፀፁፂፃፄፅፆፇፈፉፊፋፌፍፎፏፐፑፒፓፔፕፖፗፘፙፚ፠፡።፣፤፥፦፧፨፩፪፫፬፭፮፯፰፱፲፳፴፵፶፷፸፹፺፻፼€"
