# Project settings
# this is the WANDB project for experiment tracking
project: "Ethio-ASR" 

# this is the directory to save the models 
output_dir: "inprogress/Ethio-ASR" 

# random seed for the experiment 
seed: 42

# Model settings
pretrained_model: "facebook/w2v-bert-2.0" # "facebook/mms-300m"  
freeze_feature_encoder: true
add_final_layer_adapter: true

# Training settings
batch_size: 8
gradient_accumulation_steps: 4
num_epochs: 25
max_steps: 1000
learning_rate: 0.00003 # or 0.0005 for "facebook/mms-300m"  
warmup_ratio: 0.1
fp16: false
bf16: true
gradient_checkpointing: true
save_steps: 100
eval_steps: 100
logging_steps: 5
save_total_limit: 2

# Data settings
# if use_custom_dataset is true, then dataset_path is the path to the custom dataset on disk
# if use_custom_dataset is false, then dataset_path is the dataset repo name on the HF hub
use_custom_dataset: false
# if from HF hub, use the repo name badrex/kinyarwanda-speech-500h
dataset_path: "badrex/waxalNLP-dataset-1k"  
train_split: "train"
eval_split: "validation"
language: "amh"

# Data sampling settings (for debugging purposes)
sample: false
sample_size: 1000

# Text preprocessing settings
# Character set allowed in transcriptions - customize based on language and script
add_language_tokens: false
apply_accent_replacements: true

character_set: " !#$%&'*+,-.0123456789=?@abcdefghijklmnopqrstuvwxyzሀሁሂሃሄህሆሇለሉሊላሌልሎሏሐሑሒሓሔሕሖሗመሙሚማሜምሞሟሠሡሢሣሤሥሦሧረሩሪራሬርሮሯሰሱሲሳሴስሶሷሸሹሺሻሼሽሾሿቀቁቂቃቄቅቆቇቈቊቋቌቍቐቑቒቓቔቕቖቘቚቛቜቝበቡቢባቤብቦቧቨቩቪቫቬቭቮቯተቱቲታቴትቶቷቸቹቺቻቼችቾቿኀኁኂኃኄኅኆኇኈኊኋኌኍነኑኒናኔንኖኗኘኙኚኛኜኝኞኟአኡኢኣኤእኦኧከኩኪካኬክኮኯኰኲኳኴኵኸኹኺኻኼኽኾዀዂዃዄዅወዉዊዋዌውዎዏዐዑዒዓዔዕዖዘዙዚዛዜዝዞዟዠዡዢዣዤዥዦዧየዩዪያዬይዮዯደዱዲዳዴድዶዷዸዹዺዻዼዽዾዿጀጁጂጃጄጅጆጇገጉጊጋጌግጎጏጐጒጓጔጕጘጙጚጛጜጝጞጟጠጡጢጣጤጥጦጧጨጩጪጫጬጭጮጯጰጱጲጳጴጵጶጷጸጹጺጻጼጽጾጿፀፁፂፃፄፅፆፇፈፉፊፋፌፍፎፏፐፑፒፓፔፕፖፗፘፙፚ፠፡።፣፤፥፦፧፨፩፪፫፬፭፮፯፰፱፲፳፴፵፶፷፸፹፺፻፼€"
