# Project settings
# this is the WANDB project name
project: "Ethio-ASR"

# this is the output directory for  saving the model and processor 
output_dir: "inprogress/Ethio-ASR"

# set random seed for reproducibility
seed: 42

# Model settings
pretrained_model:   "facebook/w2v-bert-2.0" #"facebook/mms-300m" # 
freeze_feature_encoder: true
add_final_layer_adapter: true 

# Training settings
batch_size: 4
gradient_accumulation_steps: 8
num_epochs: 25
max_steps: 18400
learning_rate: 0.00005 # or 0.0005 for "facebook/mms-300m"  
warmup_ratio: 0.1
fp16: false
bf16: true
gradient_checkpointing: true
save_steps: 800
eval_steps: 800
logging_steps: 5
save_total_limit: 2

# Data settings
# if use_custom_dataset is true, then dataset_path is the path to the custom dataset on disk
# if use_custom_dataset is false, then dataset_path is the dataset repo name on the HF hub
use_custom_dataset: true
# if from HF hub, use the repo name badrex/kinyarwanda-speech-500h
dataset_path: "./Ethio-ASR/waxal_dataset_x/"   
train_split: "train"
eval_split: "validation"
language: "all"

# Data sampling settings (for debugging purposes)
sample: true
sample_size: 197634 


## Text preprocessing settings
# Character set allowed in transcriptions - customize based on language and script
add_language_tokens: false
apply_accent_replacements: true
character_set: " !#$%&'*+,-.0123456789=?@abcdefghijklmnopqrstuvwxyzሀሁሂሃሄህሆሇለሉሊላሌልሎሏሐሑሒሓሔሕሖሗመሙሚማሜምሞሟሠሡሢሣሤሥሦሧረሩሪራሬርሮሯሰሱሲሳሴስሶሷሸሹሺሻሼሽሾሿቀቁቂቃቄቅቆቇቈቊቋቌቍቐቑቒቓቔቕቖቘቚቛቜቝበቡቢባቤብቦቧቨቩቪቫቬቭቮቯተቱቲታቴትቶቷቸቹቺቻቼችቾቿኀኁኂኃኄኅኆኇኈኊኋኌኍነኑኒናኔንኖኗኘኙኚኛኜኝኞኟአኡኢኣኤእኦኧከኩኪካኬክኮኯኰኲኳኴኵኸኹኺኻኼኽኾዀዂዃዄዅወዉዊዋዌውዎዏዐዑዒዓዔዕዖዘዙዚዛዜዝዞዟዠዡዢዣዤዥዦዧየዩዪያዬይዮዯደዱዲዳዴድዶዷዸዹዺዻዼዽዾዿጀጁጂጃጄጅጆጇገጉጊጋጌግጎጏጐጒጓጔጕጘጙጚጛጜጝጞጟጠጡጢጣጤጥጦጧጨጩጪጫጬጭጮጯጰጱጲጳጴጵጶጷጸጹጺጻጼጽጾጿፀፁፂፃፄፅፆፇፈፉፊፋፌፍፎፏፐፑፒፓፔፕፖፗፘፙፚ፠፡።፣፤፥፦፧፨፩፪፫፬፭፮፯፰፱፲፳፴፵፶፷፸፹፺፻፼€"

